FROM apache/spark:3.5.0

USER root

RUN apt-get update && apt-get install -y python3 python3-pip && \
    pip3 install pyspark

USER spark

CMD ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", \
     "spark://spark-master:7077"]