FROM apache/spark:3.5.0

USER root

# Install Python and dependencies
RUN apt-get update && apt-get install -y python3 python3-pip && \
    pip3 install pyspark

USER spark

EXPOSE 8080 7077

CMD ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]